pipeline {

    agent any

    stages {

        stage('Clone Code') {

            steps {

                git 'https://github.com/username/docker-jenkins-demo.git'

            }

        }

        stage('Build Docker Image') {

            steps {

                sh 'docker build -t demo-app:v1 .'

            }

        }

    }

}